### PR TITLE
adding entrypoint vs cmd guidelines

### PR DESCRIPTION
**Pull request by adimania**

### CODE REVIEW

**Comment by scollier** [comment]
ping @eliskasl 

@adimania I'm ok with merging this.  I would like to see some examples though, when to use which.  I think that might be some of the value of this documentation.  In addition, might be worth mentioning that even though you can set an entrypoint in the Dockerfile, it can be overridden at runtime with --entrypoint.

**Comment by adimania** [comment]
added more examples and some more explanation.

**Comment by scollier** [comment]
LGTM.  @eliskasl

**Comment by eliskasl** [comment]
just minor typos, otherwise LGTM.

**Comment by scollier** [comment]
Thanks @eliskasl 

@adimania Please fix those spelling errors and we'll merge.

**Pull request merged**
