### PR TITLE
Openshift

### PR DESCRIPTION
**Pull request by eliskasl**

### CODE REVIEW

**Comment by eliskasl** [comment]
@bparees, could you please have a look when you find a minute? Maybe you can think of something else related to these topics/commits that should also be covered in best practices...

**Comment by bparees** [comment]
not sure what this doc says in general about VOLUMEs but that might be something else to mention. openshift volumes aren't all that different in usage from standard docker volumes though.

one major topic for openshift is not running as root, and not running as a specific user, as discussed here under support arbitrary uids: https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines

**Comment by eliskasl** [comment]
@bparees, thanks, I'll check what we have on volumes. root at al will be coming in another PR :)

**Comment by baude** [comment]
LGTM

**Pull request merged**
